### ISSUE TITLE
Query regarding Vector DB

### ISSUE THREAD

**Issue by Himansh12u** [pinecone-io/canopy#185]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

Can we use canopy with some other Vector Database apart from Pinecone ? I f not So can u please add this feature as well.

### Describe alternatives you've considered

NA

### Who will this benefit?

NA

### Are you interested in contributing this feature?

NA

### Anything else?

NA

**Comment by miararoy** [comment]
Hi @Himansh12u 

Right now we only implemented Pinecone Support, but we are already in touch with external contributors to add more vector dbs in.

We soon plan on adding features around sparse-dense vector search that are Pinecone Unique, that means that in the future we will have limited support for some features on other VDBs

that said, this is an open-source project and we welcome any contribution from the community. 

if you are building an AI application , I highly recommend [trying pinecone](https://app.pinecone.io/?sessionType=signup) not only because i work here, our free tier is quite extensive and useful for app builders. 

Closing this issue for now, and thanks for flagging this request.
