### ISSUE TITLE
[Feature] Update dependency to support Pydantic > 2.0.0

### ISSUE THREAD

**Issue by InbarShirizly** [pinecone-io/canopy#260]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

Currently cannopy pydantic version in poetry is : `pydantic = "^1.10.7"`
When we want to work with applications using pydantic 2 -> it makes it very hard to work with the product and forces downgrades in other libraries

### Describe alternatives you've considered

We are using now pydnatic 1 in our application, which cost us refactoring

### Who will this benefit?

every user trying to add canopy to a poetry project that contains requirement for updated pydantic

**Comment by igiloh-pinecone** [comment]
Hi @InbarShirizly,

This is a tough one, since there are other users who are in the exact opposite position - their existing production code is already using pydantic 1.x.x, and a hard requirement for >2.0.0 might be breaking for them.  
In addition, some of the underlying dependencies that Canopy uses still support pydantic 1 only.

We will look into this, and see if there's an easy way to support both needs, without too many hassle for users.

**Comment by charan223** [comment]
+1 same issue, need support for pydantic 2
